// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("glowing.projections")]
[assembly: AssemblyProductAttribute("glowing")]
[assembly: AssemblyDescriptionAttribute("glowing-wookie")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
